<?php

$title = 'Usuń zawodnika';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Czy jesteś pewien, że chcesz usunąć zawodnika:
    '<?= $this->escapeHtml($swimmer->firstName).' '.$this->escapeHtml($swimmer->lastName) ?>'?
</p>
<?php
$url = $this->url('swimmers', [
    'action' => 'delete',
    'id' => $swimmer->id,
]);
?>
<form action="<?= $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?= (int)$swimmer->id; ?>"/>
        <input type="submit" name="del" value="Tak"/>
        <input type="submit" name="del" value="Nie"/>
    </div>
</form>